export const IMAGES = {
    spaceBg: '/images/spaceBgSquare.png',
    gomzDetective: '/images/gomzDetective.png',
    gomzWarSpaceShip: '/images/gomzWarSpaceShip.png',
    gomzWar: '/images/gomzWar.png',
    gomzSoldier: '/images/gomzSoldier.png',
    gomzSoldierBg: '/images/gomzSoldierBg.png',
    gomzAstronaut: '/images/gomzAstronaut.png',
    gomzSpaceship: '/images/gomzSpaceship.png',
    gomzSpace: '/images/gomzSpace.png',
    gomzStory1Bg: '/images/gomzStory1Bg.png',
    gomzStory1Char: '/images/gomzStory1Char.png',
    gomzStory2: '/images/gomzStory2.png',
    gomzStory3: '/images/gomzStory3.png',
    gomzStory4: '/images/gomzStory4.png',
    gomzInnovate: '/images/gomzInnovate.png',
    gomzRebel: '/images/gomzRebel.png',
    gomzTogether: '/images/gomzTogether.png',
    cityBg: "/images/cityBg.png",
    cityBgLong: "/images/cityBgLong.png",
    gomzArtist: '/images/gomzArtist.png',
    logos: {
        main: '/images/logos/main.png',
        discord: '/images/logos/discord.png',
        twitter: '/images/logos/twitter.png',
        gomzWord: '/images/logos/gomzWord.png',
        gomzWordDude: '/images/logos/gomzWordDude.png',
        betterWorldBlue: '/images/logos/betterWorldBlue.png',
        betterWorldPurpleBox: "/images/logos/betterWorldPurpleBox.jpg"
    },
    team: {
        mj: "/images/team/1.png",
        eric: "/images/team/2.png",
        ian: "/images/team/3.png",
        serena: "/images/team/4.png",
        jay: "/images/team/5.png",
        jieun: "/images/team/6.png",
        seungan: "/images/team/7.png",
        seonghyun: "/images/team/8.png",
    }
}