export const IMAGES = {
    spaceBg: '/images/spaceBgSquare.png',
    gomzAstronaut: '/images/gomzAstronaut.png',
    gomzStory1: '/images/gomzStory1.png',
    gomzStory2: '/images/gomzStory2.png',
    gomzStory3: '/images/gomzStory3.png',
    gomzStory4: '/images/gomzStory4.png',
    gomzInnovate: '/images/gomzInnovate.png',
    gomzRebel: '/images/gomzRebel.png',
    quote: '/images/quote.png',
    gomzArtist: '/images/gomzArtist.png',
    gomzPlanet: '/images/gomzPlanet.png',
    appMain: '/images/appMain.png',
    appForum: '/images/appForum.png',
    document: '/images/document.png',
    gomzCards: '/images/gomzCards.png',
    gomzHeart: '/images/gomzHeart.png',
    gomzStore: '/images/gomzStore.png',
    circle: '/images/circle.png',
    gomzMainAstronautGif: '/images/gomzMainAstronaut.gif',
    gomzMainAstronaut: '/images/gomzMainAstronaut.png',
    mintingProcess: '/images/mintingProcess.png',
    clickmetoenter: '/images/clickmetoenter.png',
    menuIcon: '/images/menuIcon.png',
    cancelIcon: '/images/cancelIcon.png',
    starDusts: '/images/starDusts.png',
    starDusts2: '/images/starDusts2.png',
    starDusts3: '/images/starDusts3.png',
    circleLeftArrow: '/images/circleLeftArrow.png',

    logos: {
        main: '/images/logos/main.png',
        discord: '/images/logos/discord.png',
        twitter: '/images/logos/twitter.png',
        betterWorld: '/images/logos/betterWorld.png',
        betterWorldSecondary: '/images/logos/betterWorldSecondary.png',
        gomzWord: '/images/logos/gomzWord.png',
        gomzMotto: '/images/logos/gomzMotto.png',
        webeWord: '/images/logos/webeWord.png',
        betterWorldPrimaryLogo: '/images/logos/betterWorldPrimaryLogo.png',
        webePrimaryIcon: '/images/logos/webePrimaryIcon.png',
        webeWhiteLogo: '/images/logos/webeWhiteLogo.png',
    },
    team: {
        mj: "/images/team/1.png",
        eric: "/images/team/2.png",
        ian: "/images/team/3.png",
        serena: "/images/team/4.png",
        jay: "/images/team/5.png",
        jieun: "/images/team/6.png",
        seungan: "/images/team/7.png",
        seonghyun: "/images/team/8.png",
    }
}